// Generated by FlutterFire CLI.
// Run `flutterfire configure` in your project root to replace this file
// with your actual Firebase project configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  // TODO: Replace these values by running: flutterfire configure
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiTZGtXDwHicHcvR1ZTkuZwU890M9mJjQ',
    appId: '1:938250837519:android:ad233ebd5e88f48f0ccd7a',
    messagingSenderId: '938250837519',
    projectId: 'authflow-csc4360',
    storageBucket: 'authflow-csc4360.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf58mI0ZNyYwxd5wNVrz8c4AmSPQYgwAE',
    appId: '1:938250837519:ios:6245cc38337564bf0ccd7a',
    messagingSenderId: '938250837519',
    projectId: 'authflow-csc4360',
    storageBucket: 'authflow-csc4360.firebasestorage.app',
    iosBundleId: 'com.example.authenticationApp',
  );

}